# This is the base file. It defines the service structures that are common
# across all environments. Environment-specific files will override these.
services:
  nginx:
    image: nginx:latest
    networks:
      - pacmusic-network
    depends_on:
      - pacmusic-1
      - pacmusic-2

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Mount the initialization script to create tables and data on first run
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pacmusic-network

  pacmusic-1:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - pacmusic-network
    depends_on:
      - postgres

  pacmusic-2:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - pacmusic-network
    depends_on:
      - postgres
