services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    # Use local bind mounts instead of named volumes
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot_data/conf:/etc/letsencrypt
      - ./certbot_data/www:/var/www/certbot
    networks:
      - pacmusic-network
    depends_on:
      - pacmusic-1
      - pacmusic-2

  certbot:
    image: certbot/certbot
    # Use local bind mounts instead of named volumes
    volumes:
      - ./certbot_data/conf:/etc/letsencrypt
      - ./certbot_data/www:/var/www/certbot
    # IMPORTANT: Remember to update the domains and email in init-letsencrypt.sh
    # The command is now run by the script, not here.

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pacmusic-network

  pacmusic-1:
    build:
      context: ./app
    container_name: pacmusic-1
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - pacmusic-network
    depends_on:
      - postgres

  pacmusic-2:
    build:
      context: ./app
    container_name: pacmusic-2
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - pacmusic-network
    depends_on:
      - postgres

volumes:
  # Only the postgres volume is a named volume now
  postgres-data:

networks:
  pacmusic-network:
